Added more tests and coverage

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -13,8 +13,11 @@ jobs:
           go-version: '1.20'
       - name: Vet
         run: go vet -v ./...
-  linux-test:
-    runs-on: ubuntu-latest
+  test:
+    strategy:
+      matrix:
+        os: [ ubuntu-latest, macos-latest ]
+    runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
       - name: Set up Go
@@ -24,16 +27,19 @@ jobs:
       - name: Build
         run: go build -v ./...
       - name: Test
-        run: go test -v ./...
-  macos-test:
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: '1.20'
-      - name: Build
-        run: go build -v ./...
-      - name: Test
-        run: go test -v ./...
+        run: go test -race -v ./... -coverprofile coverage.out -covermode count
+      - name: Coverage
+        env:
+          TESTCOVERAGE_THRESHOLD: 90
+        run: |
+          echo "Checking test coverage is above threshold ..."
+          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold."
+              echo "Failed"
+              exit 1
+          fi
